# Generated by Django 6.0.4 on 2026-05-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainrecord',
            name='contract_address',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='blockchainrecord',
            name='network_name',
            field=models.CharField(default='simulated', max_length=80),
        ),
    ]
